### ISSUE TITLE
Incorrect installation via pip

### ISSUE THREAD

**Issue by Bloodrammer** [analysiscenter/dataset#225] opened 2018-03-15 11:43 UTC
Hey folks,
I've just installed the latest version of dataset using pip (python 3.5.2), so that I could try [this example](https://github.com/analysiscenter/dataset/blob/master/examples/opensets/mnist_model3.py). However, when I tried to import best_practice, it failed with something like `ImportError:  cannot import enable_best_practice`. I only managed to solve the problem by installing the package as a submodule, which seems fishy. You probably forgot to add something somewhere - maybe setup.py.

Also, when I managed to successfully install dataset, I've encountered the same problem as [#224](https://github.com/analysiscenter/dataset/issues/224), but that's a whole different story

**Comment by roman-kh** [comment] 2018-03-15 17:26
Thanks for letting us know.
However, I could not reproduce the issue. I installed the package today several times on different computers with pip and every time without any problems.

I reckon you might try `-U` option for pip to ensure that a new version of `Dataset` is installed even if the old one exists.

**Comment by roman-kh** [comment] 2018-03-21 07:02
Closing as the problem seems to be solved.

**Closed by roman-kh** 2018-03-21 07:02 UTC
